name : Release Drafter

on: 
  push: 
    bracches:
      - master
    pull_request:
      types: [Merged]
    permissions:
      contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull_requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITGUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}